### ISSUE TITLE
Task flags

### ISSUE THREAD

**Issue by omeid** [omeid/slurp#13]
Introduce a mechanism to pass flags to specific tasks.

```go
Task("help", func(c *slurp.C) error {
	
	tag := c.String("tag", "default", "the build tag to use.")

	fmt.Println("%T %v", tag, tag)
	return nil
	})
})
```

```sh
$ slurp embed
string default
$ slurp embed -tag=prod
string prod
```

Possible limitations, no way to pass "args", so `flags.Args()` would always return `[]string{}`.

**Comment by omeid** [comment]
Perhaps this is a better approach which allows passing flags even when tasks are running as dependencies.

```sh
$ slurp embed
string default
$ slurp -embed-tag=prod embed # or  slurp embed -embed-tag=prod
string prod
```

**Comment by omeid** [comment]
```go
Task("help", func(c *slurp.C) error {
    tag := c.GlobalString("tag", "tag", "the build tag to use.")

    fmt.Println("%T %v", tag, tag)
    return nil
    })
})
```
```
$ slurp embed
string default
$ slurp -tag=prod embed
string prod
```

**Comment by kdar** [comment]
Seems like this would conflict with the cmd/slurp command arguments. 
I think it would be nice to be able to specify tags after the task names, like what was originally proposed, but I know the code assumes all the arguments are task names. 

You could either do something like
```
$ slurp embed -- -tag=prod
```
or make it so slurp only accepts one task, or make it so tasks have to be separated by commas. e.g.
```
$ slurp embed,embed2 -tag=prod
```

Also, it's not necessary, but with gulp you can use whatever library you want to parse arguments. It would be nice if we could do the same here instead of having to use functions in *slurp.C.

**Comment by omeid** [comment]
The second example is using 'c.GlobalString', that would include flags that listed before tasks, the example before that is using `c.String()` which would be the flags passed after the task name.

Nothing is stop you from using `os.Args` to parse the flags as you please, it would create inconsistency.

But after testing this idea for a couple of days it doesn't seem very helpful and printing a help and list of message is not possible without running tasks. So I am considering approach this by introducing a new parameter to b.Task that takes a flag.FlagSet or something similar to codegangsta/cli flags and see how it works.

**Comment by omeid** [comment]
This adds too much complexity and I don't see a real world use for it. If you want to give a good example of why you need this. I will consider it.
